#docker compose --env-file .release.env up -d --build
services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  redis_storage:
    image: redis:7-alpine
    container_name: redis_storage
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis_storage_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: mkk_luna_api
    restart: unless-stopped
    environment:
      APP_ENV: release
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}

      MYSQL_DSN: ${MYSQL_DSN}

      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      TOKEN_ISSUER: ${TOKEN_ISSUER}
    ports:
      - "${HTTP_SERVER_PORT}:5555"
    depends_on:
      mariadb:
        condition: service_healthy
      redis_storage:
        condition: service_healthy
    networks:
      - app_network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - app_network

volumes:
  mariadb_data:
  redis_storage_data:
  prometheus_data:

networks:
  app_network:
    driver: bridge
